### ISSUE TITLE
Black Dragon Scale Tasset

### ISSUE THREAD

**Issue by jasonh99** [illusionistpm/ddo-gear-planner#10]
The item (Legendary Black Dragon Scale Tasset) listed in the ap only has 1 property, It looks like it was updated on the 11/11/2020 so I assume the last lot ofdata you imported from the wiki was after that. So perhaps there is an issue: (With the unkonw/strange feature at the beginning of the item?) https://ddowiki.com/page/Item:Legendary_Black_Dragonscale_Tasset
Is there somethign that can be done at the wiki end to help this through?

**Comment by jasonh99** [comment]
A few other items are the same - Flower Boots - From Feywild.

**Comment by illusionistpm** [comment]
Odd. Good catch. I'll take a look.

**Comment by illusionistpm** [comment]
Not actually sure why it didn't work before, but I tweaked the parser and it seems to be happy now. It fixed those plus a handful of random other items that no one had noticed.
