### ISSUE TITLE
Augments - Updated Spreadsheet

### ISSUE THREAD

**Issue by jasonh99** [illusionistpm/ddo-gear-planner#11]
Updated all Augment Scaling that have changed
[augments.xlsx](https://github.com/illusionistpm/ddo-gear-planner/files/5607933/augments.xlsx)

**Comment by illusionistpm** [comment]
Thanks so much. I had zero motivation to get that updated and felt bad about it. 🙂 I'll get it in tonight.

**Comment by illusionistpm** [comment]
Pushed the new numbers.
