### ISSUE TITLE
parse_item_pages.py  - Add Sacred

### ISSUE THREAD

**Issue by jasonh99** [illusionistpm/ddo-gear-planner#12]
Need to Add "Sacred" to this Section (eg: https://ddowiki.com/page/Item:Gloryborne_Gloves)

```
def strip_bonus_types(name):
    for type in ['Insightful', 'Exceptional', 'Enhanced', 'Quality', 'Profane', 'Competence', 'Equipment', 'Equipped', 'Inherent']:
        if name.startswith(type):
            name = name[len(type)+1:]
```

**Comment by jasonh99** [comment]
IVe changed to code and pushed for approval.

**Comment by illusionistpm** [comment]
Hm. I don't see your changes for this issue or the other one. You can submit them by opening a Pull Request from the tab row up top.

**Comment by jasonh99** [comment]
I think Ive got this right this time. closing.
