### ISSUE TITLE
Well Rounded

### ISSUE THREAD

**Issue by jasonh99** [illusionistpm/ddo-gear-planner#15]
The code looks like Well Rounded should show a profane bonus to each Stat, (Str, Dex, Int, Wis, Con, Cha) but it doesnet seem to. It's listed as Well Rounded Affix Only in build_affix_groups.py  and code looks ok.
Ive looked at the cached data for items and they look ok too.

sample cached data pulled from wiki.
`<li><span class="has_tooltip" style="cursor: pointer; border-bottom: 1px dashed #999999;"><a href="/page/Ability" title="Ability">Profane Well Rounded +2</a><img alt="Icon tooltip.png" src="/images/thumb/Icon_tooltip.png/10px-Icon_tooltip.png" width="10" height="8" style="vertical-align: super" srcset="/images/Icon_tooltip.png 1.5x" /><span class="tooltip" style="z-index: 10000; border: 1px solid #333333; background-color: #EEEEEE; border-radius: 3px; box-shadow: 3px 5px 10px; top: 14px; left: -125px; text-align: center; padding: 5px; width: 450px; max-width: 450px; cursor: text; margin: 0px;"><b><a href="/page/Ability" title="Ability">Profane Well Rounded +2</a></b>: +2 <a href="/page/Profane_bonus" title="Profane bonus">profane bonus</a> to all abilities.</span></span></li>`

**Comment by illusionistpm** [comment]
Well-rounded appears to have been fixed since this issue was opened. Please reopen if you can still reproduce.
