### ISSUE TITLE
Armor Class Grouping

### ISSUE THREAD

**Issue by jasonh99** [illusionistpm/ddo-gear-planner#16]
If you are looking at Grouping (eg. Hit Points) Armour class would be a biggie as well.

**Armour Class**
Group Prefix "armor" and "Armor Bonus"

With Bonus Types
Armor Bonus ------------- From Armor (Also from Legendary Tharne's Bracers)
Insightful Armor Bonus - From Parrying Items Also adds to Saving Throus as Isightful bonus)
Quality Armor Bonus ---- (From Epic Robe of Insight, and Epic Docent of Insight)
Natural
Insightful Natural
Primal Natural ------------From Rough Hide - [Legendary Direbear Belt)](https://ddowiki.com/page/Item:Legendary_Direbear_Belt)
Artifact Natural-----------(Wayward Warrior Set)
Deflection ----------------- (From Protection Items)
Shield Bonus -------------- From Shield type itself, or from Shield Ability on item.
There is an Artifact Armour Bonus of 10 identified in the planner, but that is 10% Set bonus not a straight +10 (Eg. Knights of the Shadow Set Bonus from Ravenloft)

**Comment by jasonh99** [comment]
Added Pull Request with Synonym changes to deal with most of this.  However will need to retupe Natural Armor bonusses as "Natural", and "insightful natural" instead of "armor".

**Comment by illusionistpm** [comment]
Armor Class looks a lot better now - thanks @joenuts1!
