### ISSUE TITLE
Doubleshot bonuses are missing items?

### ISSUE THREAD

**Issue by Question2** [illusionistpm/ddo-gear-planner#41]
![image](https://user-images.githubusercontent.com/1191378/155062435-3fcfa492-c405-4d8b-8a50-268def06dd86.png)

It says there are 9 items with an enhancement bonus, but its only displaying cannith crafting trinkets. Insight bonuses say there are 4 items, but display none.

**Comment by illusionistpm** [comment]
Yeah, I broke a bunch of stuff. The site should be updated in a few minutes with the fix.

**Comment by Question2** [comment]
Thanks, but the "spell saves" affix also appears to be broken.
