### ISSUE TITLE
Searching for resonance spellpower gives potency instead

### ISSUE THREAD

**Issue by Question2** [illusionistpm/ddo-gear-planner#42]
Searching for the resonance affix gives items with potency instead, which results in way too many results and makes it hard to find items with the actual resonance affix.

Edit : Evocation focus has the same problem. Trying to search for insightful evocation focus gives me results for "insightful spell focus mastery" and it clutters up the search results.

**Comment by illusionistpm** [comment]
Working as intended. The highest values should filter to the top of the list though, so you shouldn't have to scroll far to find something good. Given 2 items with the same value, it shouldn't matter whether it's explicitly Resonance or Potency.

**Comment by Question2** [comment]
> Working as intended. The highest values should filter to the top of the list though, so you shouldn't have to scroll far to find something good. Given 2 items with the same value, it shouldn't matter whether it's explicitly Resonance or Potency.

The problem is that i am trying to find resonance items specifically. I cant tell which is resonance or potency in the list because potency keeps cluttering up the results.

Please change it back to only display resonance affixes specifically. If someone wants to display both, they can add resonance AND potency as affixes in the search, which lets you get the best of both worlds. Right now, there is no way for it to display resonance only and it is making it very difficult to search for resonance only.

This problem is happening for every spellpower item.

**Comment by illusionistpm** [comment]
What is the case where a Resonance item is preferable to Potency? As far as I'm aware, Potency is strictly equal-or-better to Resonance, since it boosts all your spellpowers including Resonance. If I'm trying to maximize my Resonance, I don't care whether it's coming from Resonance or Potency.
