### ISSUE TITLE
Mind & Matter set MRR & PRR bonuses not reflected in tracked affixes

### ISSUE THREAD

**Issue by NeighborGeek** [illusionistpm/ddo-gear-planner#61]
With the Legendary Omniscience and Legendary Tumbleweed rings equipped, the gear planner correctly shows the Mind and Matter set bonus applying, but under the tracked affixes section neither Physical Sheltering nor Magical Sheltering reflect the +30 artifact bonuses from the set.

**Comment by illusionistpm** [comment]
Resolved by PR #74
