### ISSUE TITLE
Overlap Profane Spell Focus & Quality Spell Focus

### ISSUE THREAD

**Issue by jasonh99** [illusionistpm/ddo-gear-planner#7]
There seems to be some overalp of profane spell focus and Quality spell focus becasue of how they are categorised on the items in the wiki.  (IE 2 different terms of describing the same effect)  Should I just fix that on the wiki for it to come trhough ?
EG: 
Legendary Winter Cout: Profane Spell Focus Mastery +2 - The im age says its Profane Spell Focus II
The Legendary Shattered Onyx: Profane Spell Focus II

**Comment by jasonh99** [comment]
Ive modified all tiems in the wiki to match the more popular Spell Focus Mastery - this provides consistancy with a lot of other items.

**Comment by jasonh99** [comment]
I fixed spelling on the wikik of the Quality Spell focusy Necromancy (From Necromacy)  so it should be categorised correctly here.

**Comment by jasonh99** [comment]
Legendary Slave Lords Crafting Spell Penetration Shown As Equipment, I beleive it should be types as Enhancement like other items. - Im not sure if that needs to be cahnged here or on the wiki ?

**Comment by illusionistpm** [comment]
Thanks - I'll run the data update script tonight.

**Comment by illusionistpm** [comment]
Data was updated.
