### ISSUE TITLE
Legendary Slave Lords Crafting Spell Penetration

### ISSUE THREAD

**Issue by jasonh99** [illusionistpm/ddo-gear-planner#8]
Legendary Slave Lords Crafting Spell Penetration Shown As Equipment, I beleive it should be types as Enhancement like other items. - Im not sure if that needs to be cahnged here or on the wiki ?

**Comment by jasonh99** [comment]
Well looks like I cocked that up - Have you changed this already - I think yoiu may have? Its listed as Enhancement, but it should be Equipment like it was. My appologies, I would fix the spreadsheet and upload, but hardly worth risking me messing it up for 2 items)  You must have changed the name too so it now stackes in the right group,. I think that ws my problem before and I didnt understand how the naming worked - sorry.   (Ill do some work an update the augment spredsheet if you like - ill link it once ive done)

**Comment by jasonh99** [comment]
Have you fixed this already? Looks like I made a bad call - its now groued but it should be equipment despite what I wrote above. I think i was confused by the non grouping. Fixed file attached.
[slavers.xlsx](https://github.com/illusionistpm/ddo-gear-planner/files/5606950/slavers.xlsx)

**Comment by illusionistpm** [comment]
Great, thanks!

**Comment by illusionistpm** [comment]
I think we're good now? Let me know if something's still off.
