### ISSUE TITLE
Hit Point Effects

### ISSUE THREAD

**Issue by jasonh99** [illusionistpm/ddo-gear-planner#9]
It seems the Hit point affects need consolidations.
Each Type has a different name, eg. 

Can this be consolidated in your app, or do we need to make the wiki categorise Vtality and Vitality as a type of False Life. (The latter seems like a big job and creates some inconsitancy)

False Life = Enhancement, Insightful, Quality
Lifeforce = Profane Bonus
Vitality = Vitality Bonuse

**Comment by illusionistpm** [comment]
I have some preliminary support for "synonyms": affixes that have different names but affect the same value, which should cover us here. I'll have to check on the state of it however.

**Comment by illusionistpm** [comment]
Yeah, I think the synonym stuff needs more work. I added Lifeforce to the False Life / Vitality / Hit Points group at least, so it'll at least get picked up when I finish it off.

**Comment by jasonh99** [comment]
Yeah there is some real consistancey errors in the Wilkki on False Life being called Hit Points sometimes and False Life Others.  but interestingly in the base  code for the wiki entry they all have a type of hp  `{{Hp|False Life|81}}` but that isnt whats shown once it displays.  Ill look into that a bit more.

**Comment by illusionistpm** [comment]
We should be in pretty good shape here now. Thanks @joenuts1!
